name: Deploy

on:
  push:
    branches:
    - master

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: perchunpak
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker Meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: perchunpak/superhub-fuck-ups-counter

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          ORIGIN=https://superhub.perchun.it
          REDIS_URL=${{ secrets.REDIS_URL }}
          REDIS_TOKEN=${{ secrets.REDIS_TOKEN }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
